[package]
name = "spellck"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.6", features = ["blocking", "json"] }
serde_urlencoded = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
annotate-snippets = { version = "0.9.1", features = ["color"] }
